### ISSUE TITLE
The latest ISO is not booting and saying VMLINUZ not found

### ISSUE THREAD

**Issue by shadowwalkersteam** [t2linux/archiso-t2#10] opened 2022-10-05 10:12 UTC
archlinux-t2-2022.10.01-x86_64 - Release Onimai 
I made USB pen drive with the above ISO but its not booting instead saying VMLINUZ missing.

**Comment by NoaHimesaka1873** [comment] 2022-10-05 14:55
I am aware of this issue. Sadly I'm currently in the middle of midterm exams so I'm very busy. Will be fixed when I have time to properly examine the root cause of this issue.

**Comment by Netetra** [comment] 2022-10-06 09:36
I am using a Macbook pro (13inch 2019) and have the same problem.

**Comment by NoaHimesaka1873** [comment] 2022-10-06 12:25
@shadowwalkersteam @Netetra Fixed with 2022.10.06 release. Closing as fixed.

**Closed as completed by NoaHimesaka1873** 2022-10-06 12:25 UTC
